# 个人主页配置文件，建议只修改带有【需填写】注释的部分
# 修改后直接上传到 GitHub 即可

# 基本设置
locale                   : "zh-CN" # 网站语言
# 网站标题【需填写】
title                    : "APhysickui's Personal Page"
title_separator          : "-"
# 你的名字【需填写】
name                     : &name "Zhenkui Zhou"
# 网站描述【需填写】
description              : &description "A Student of Physics"
# 主页网址（如用 GitHub Pages，格式为 https://用户名.github.io）【需填写】
url                      : "https://APhysickui.github.io"
# 子路径（通常留空即可，除非你用子目录）
baseurl                  : ""
# 首页展示图片（如有请放在 images 文件夹下）【可选】
og_image                 : "images/wanted.png"
repository               : "APhysickui.github.io" # GitHub 仓库名
teaser                   : "" # 首页预览图【可选】
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

# 评论系统（可选，建议先不填）
comments:
  provider               : # false (默认), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "lowercase"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  path                   :

# SEO 相关（可选）
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# 社交账号（建议填写常用的）
twitter:
  username               : ""
facebook:
  username               : ""
  app_id                 : ""
  publisher              : ""
og_image                 :
social:
  type                   : "Person"
  name                   : "你的名字"
  links: # 填写你的社交链接，如 GitHub、LinkedIn 等
    - "https://github.com/APhysickui"
    # - "https://linkedin.com/in/你的linkedin"
    # - "https://twitter.com/你的twitter"

# 统计分析（可选）
analytics:
  provider               :  "google-universal"
  google:
    tracking_id          :

# 作者信息【需填写】
author:
  name             : "Zhenkui Zhou" # 你的名字
  avatar           : "images/wanted.png" # 推荐放在 images 文件夹
  bio              : "A Student of Physics"
  location         : "Beijing, China"
  email            : "zzk1685419208@gmail.com"
  github           : "APhysickui"
  # 其他社交账号可按需填写

# 读取文件设置
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown 相关
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# 内容集合（可按需保留）
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  Repositories:
    output: true
    permalink: /:collection/:path/
  Notes:
    output: true
    permalink: /:collection/:path/
  Blogs:
    output: true
    permalink: /:collection/:path/
  additions:
    output: true
    permalink: /:collection/:path/
  Links:
    output: true
    permalink: /:collection/:path/

# 默认布局
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # 其他集合默认布局可按需修改

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# 输出设置
permalink: /:categories/:title/
timezone: Asia/Shanghai # 推荐用中国时区

# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# 分类/标签归档
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML 压缩
compress_html:
  clippings: all
  ignore:
    envs: development

# 主页配置完成！
# 你只需填写带有【需填写】注释的字段，图片建议放在 images 文件夹。
# 填好后上传到 GitHub Pages 仓库即可。